### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by fzwart**
- added virtual server curly braces. version 1.2.2 needs these (current version for debian wheezy)
- added some indentation which makes the config more readable

### CODE REVIEW

**Comment by arioch** [comment]
Could you also fix the tests?
By the looks of it it's caused by the indentation changes.

**Comment by fzwart** [comment]
sure, will fix 'm asap

**Comment by fzwart** [comment]
Done!

**Comment by arioch** [comment]
My apologies for the late reply, hadn't noticed you fixed them.

While merging your fixes I've noticed you show up as ```Vagrant User``` in my git history.

```
☃  git show 61cff704be80fb9f91945ba2bf40e21a5faa0949 | head -5
commit 61cff704be80fb9f91945ba2bf40e21a5faa0949
Author: Vagrant User <vagrant@dev.speakap.nl>
Date:   Mon Aug 24 10:49:08 2015 +0200

    tests now match additional curly braces and indentation
```

I'd prefer to have the proper name to each commit. 
If you could just fix that I'll merge it.

**Comment by fzwart** [comment]
I've changed the identity of the last two commits.

**Comment by arioch** [comment]
Last request, I promise! :blush: 
Could you merge those commits into a single commit?

**Pull request closed without merging**
