### PR TITLE
Support SNMP for keepalived.

### PR DESCRIPTION
**Pull request by seriv**
SNMP support can be enabled with additional arguments for the global_defs class and the corresponding template

### CODE REVIEW

**Comment by dynek** [comment]
@arioch - upvoting (if taken into account :-)) cause SNMP is a must to know keepalived's health and which node is master or backup. Thank you!!

**Comment by dynek** [comment]
@duritong - ping in case @arioch is too busy. Would be awesome to be able to manage SNMP from puppet instead of having to modify `/etc/sysconfig/keepalived` manually.

**Comment by arioch** [comment]
Also: people still use SNMP? 😨

**Comment by arioch** [comment]
Given it a second thought and added the tests myself as it only took a few minutes to do so.
Merged, thanks! 👍

**Comment by dynek** [comment]
> @dynek I don't see how pinging people without commit access could speed things up. 😉

Wrong assumption, I thought @duritong had commit/merge rights.

**Comment by arioch** [comment]
For future reference: for urgent requests just mail me directly, don't rely on (filtered) GitHub mails.
Shouldn't be too hard to find my address, right? 😄

**Pull request closed without merging**
