### PR TITLE
Split integer and value check into separate if statements

### PR DESCRIPTION
**Pull request by erikanderson**
Remove the possibility that a comparison will be done between a string and an integer by failing earlier

Fixes: 

```
2015-10-07 09:42:19,045 ERROR [puppet-server] Puppet Evaluation Error: Comparison of: String < Integer, is not possible. Caused by 'A String is not comparable to a non String'.
```

Closes https://github.com/arioch/puppet-keepalived/issues/79

### CODE REVIEW

**Comment by danieldreier** [comment]
@arioch can we get a merge on this? We're unable to use this module with puppet 4 until this is resolved.

**Comment by mkrakowitzer** [comment]
This PR did not work for me as is on puppet 4. I had to nest the second if statements into the previous one. ie: 

```puppet
  if (!is_integer($virtual_router_id)) {
    fail('virtual_router_id must be an integer >= 1 and <= 255')
    if ($virtual_router_id < 1 or $virtual_router_id > 255) {
      fail('virtual_router_id must be an integer >= 1 and <= 255')
    }
  }
```

**Comment by arioch** [comment]
Could you rebase that onto current HEAD?

**Comment by erikanderson** [comment]
Not sure if this was what you meant @arioch. Either typecasting or my approach resolves the problem

**Comment by danieldreier** [comment]
yeah, I think that now that it's type cast we don't need this -- is that correct @erikanderson?

**Comment by erikanderson** [comment]
Yeah, the fix already committed works for puppet 3 and 4

**Pull request closed without merging**
