### PR TITLE
add define keepalived::lvs::real_server::misc_check

### PR DESCRIPTION
**Pull request by arnd**
The current way to specify checks for keepalived::lvs::real_server within an options parameter
has at least two problems:
 * you can't specify more than one check of a certain type (e.g. two ore more checks of type MISC_CHECK, which is what we really need in our setup)
 * there is no validation for the CHECK syntax / options

This PR fixes that for MISC_CHECK, by introducing a new define for this kind of check.

### CODE REVIEW

**Comment by arioch** [comment]
Looking good so far but it seems to fail on some versions due to rspec incompatibility:

```
Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling 
the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` 
instead. Called from /home/travis/build/arioch/puppet-keepalived/spec/unit/facter/keepalived_version_spec.rb:19.
```

**Comment by arnd** [comment]
Hi, thanks for the feedback. I updated the PR.

**Comment by arioch** [comment]
Could you push that branch again? I can't seem to pull it from your fork...

**Comment by arnd** [comment]
Hmm strange. I'll try to create a new PR and close this one.

**Pull request closed without merging**
