### PR TITLE
Add support for firewall marks in virtual_server config

### PR DESCRIPTION
**Pull request by jadestorm**
Hi there!  This PR adds some support for fwmark based virtual_servers.  Hopefully pretty straightforward!

Let me know if you need me to adjust anything or have questions!

### CODE REVIEW

**Comment by jadestorm** [comment]
Interesting, I see a lot of travis-ci tests failed but ... they all appear to be unrelated to the code?

**Comment by arioch** [comment]
They're indeed unrelated to the code.
It's caused by 1 or 2 gems that are incompatible with Ruby <2.0.

I'll add some version clauses to the Gemfile when time permits.

Other than that thanks for your PR!
Could rebase (fixup) those 4 commits into a single one? And also an example snippet in README.md would be greatly appreciated. 👍

**Comment by jadestorm** [comment]
Sure thing, interesting -- had never seen rebaseing to cleaning things up before!  Found a good doc on it here:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

I might add a little note to the contributing section for it while I'm at it.

**Comment by arioch** [comment]
Basically ```fixup``` is the merge mechanism one you need.

```
git rebase -i HEAD~4
pick => fixup
save & exit
git push origin master --force
```

**Comment by arioch** [comment]
Something went wrong there. You've ended up with 9 commits instead of your original 4.

This should get back to start:
```
git rebase -i 97a508a74b23938816259d82e9db2b927b7de1a0
exit, no need to save
```

**Comment by jadestorm** [comment]
Sorry yeah you were seeing me trying to figure out the cray.  ;D  Should be all good now!

**Comment by jadestorm** [comment]
Note the addition to the contributing message at the bottom of the README -- in case you don't like how that's worded or something.  =)

**Comment by arioch** [comment]
Finally got around to merging.
Thanks again! 👍

**Pull request closed without merging**
